controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
newsletter_subscribe:
    path: /newsletter/subscribe
    methods: ['POST']
    controller: App\Controller\NewsletterController::subscribe